### ISSUE TITLE
[LandingPage] Update content of Homepage from MKT

### ISSUE THREAD

**Issue by Dpthao245** [aura-nw/landing-page#111]
**Describe the bug**
Update content of Homepage from MKT

**To Reproduce**
1. Go to https://aura.network/
2. See error

- [x] Mobile: 3 boxes: thêm 3 dấu chấm giống bản Mobile trên Figma Roadmap

![image](https://user-images.githubusercontent.com/72438169/160321390-443d666f-26c9-4225-906f-ecb6ad498a50.png)

- [x] Mobile & Desktop: Xoá chữ IEO tại Q2-2022

![image](https://user-images.githubusercontent.com/72438169/160321692-944e55dc-2be5-4034-84f0-6cddfe50829c.png)

- [x] Mobile & Desktop: Chỉnh roadmap để khi mở lên sẽ về đúng Quý hiện tại

Ví dụ: hiện tại Q2-2022
![image](https://user-images.githubusercontent.com/72438169/160322001-92fc272c-54d0-443c-8a74-250754ae6317.png)
![image](https://user-images.githubusercontent.com/72438169/160322031-800a6c94-e585-4bae-a7cd-584ea4a89d4e.png)

- [x] Mobile: FAQ Chỉnh lại cỡ chữ nhỏ hơn cho các Questions vì hiện đang to hơn các cỡ chữ khác
Size 16

**Comment by NgocAnh7278** [comment]
28/03/2022: Ngoc Anh updates:

- [ ] Roadmap: Cập nhật màu chữ Timeline và màu button next, back như figma: https://www.figma.com/file/u9FVvZYiA6pTpoZYqmHpf1/AuraNetwork---Landingpage?node-id=0%3A1
![image](https://user-images.githubusercontent.com/40628286/160362479-a8a3d5b0-5d41-454b-aa9b-4730b9e5a4a5.png)

- [ ] Footer: Cập nhật Title và dòng chữ mô tả
![image](https://user-images.githubusercontent.com/40628286/160362682-0fb8cbb6-bef6-457e-ab35-c7449c12e04a.png)
Let's talk!
We’d love to hear from you, we’re here to answer all your questions.
support@aura.network -> 

_Note_:
Email "support@aura.network ->" được gạch dưới chân, click vào -> hiển thị tab để gửi email đến support@aura.network.

- [ ] Cập nhật tất cả button next, back ở ROADMAP, Advisors, teams như thiết kế.
