### ISSUE TITLE
[News] Some News' issues on desktop

### ISSUE THREAD

**Issue by hangpham23** [aura-nw/landing-page#112]
1. Tabs orders are different to Figma design
2. Animation and shadow color while hovering on post are different to Figma design
3. Seach box is different to Figma design
4. Social is missing LinkedIn 
5. News => Insights (menu drop list also)
6. Figma design not show number contact : 732-528-4945
7. Footer menu options are on the center instead of left side
8. Post text's color is different to Figma design
9. Seach button display in wrong position [Firefox, Safari]
1. Go to https://aura.network/news/

**Expected behavior**
- [x]  1. Expected: SAFE , PARTNERSHIP, NFT101, CAREERS
- [x] 2. Animation and shadow color while hovering on post display as Figma design 
- [ ] 3. Search box display as Figma design
- [x] 4. Social has all 5 options
- [x] 5. News => Insights
- [x] 6. Remove number contact 732-528-4945
- [x] #119
- [x] 8. Post text display as Figma design
- [ ] 9. Search button display as Figma design
![image_2022_03_28T07_23_43_721Z](https://user-images.githubusercontent.com/102220123/160354110-28feb5c2-7fac-46d2-a50f-c13a5f7ad038.png)

<img width="1023" alt="Screen Shot 2022-03-28 at 14 02 33" src="https://user-images.githubusercontent.com/102220123/160344162-6e4f1c7e-6ae0-48be-a60b-2cc12be35e26.png">

**Screenshots**

![image_2022_03_28T03_04_16_238Z](https://user-images.githubusercontent.com/102220123/160323249-334c7397-d2fc-4ff2-bfc8-507abc792c45.png)
![image_2022_03_28T03_06_41_840Z](https://user-images.githubusercontent.com/102220123/160323269-3fc2b406-bc07-4ada-9bcc-2449744573bf.png)
<img width="1202" alt="Screen Shot 2022-03-28 at 10 12 35" src="https://user-images.githubusercontent.com/102220123/160323287-99ae94d2-6289-4357-b3a9-e2d9d982194f.png">
<img width="480" alt="Screen Shot 2022-03-28 at 09 59 42 (1)" src="https://user-images.githubusercontent.com/102220123/160324115-921f036a-b9a5-40eb-a3cc-35cc005960ea.png">
![image_2022_03_28T04_36_52_739Z](https://user-images.githubusercontent.com/102220123/160339042-cd20f862-5ac9-41cb-8a51-8353eda230c6.png)

![image_2022_03_28T06_30_14_371Z](https://user-images.githubusercontent.com/102220123/160339342-ec99ff4b-27a1-4764-80f6-098418c6ae8c.png)
<img width="1023" alt="Screen Shot 2022-03-28 at 14 18 41" src="https://user-images.githubusercontent.com/102220123/160346714-d7a1c54e-f7b8-40e4-b064-5416fc452ee7.png">

<img width="486" alt="Screen Shot 2022-03-28 at 15 59 14" src="https://user-images.githubusercontent.com/102220123/160365240-eee6883f-849a-4dc4-84fb-ef5a8b6d7f01.png">

**Desktop (please complete the following information):**
 - Browser [ chrome, firefox, safari]

- Window
- Browser [chrome]

**Comment by letrieuthien** [comment]
search bar đã thay đổi layout nên task đổi design search này dev sẽ ko check done nữa, sẽ thực hiện ở ticket
https://github.com/aura-nw/landing-page/issues/64
