### ISSUE TITLE
[Landing Page] Some issue on Landing page ( Narrow, wide screen on mobile phone )

### ISSUE THREAD

**Issue by vitrantuong** [aura-nw/landing-page#115]
**ISSUE 01**
**Describe the bug**

- [x] Mobile & Desktop: Cập nhật vị trí tất cả button next, back ở ROADMAP, Advisors, teams như thiết kế.

**Expected behavior**
![image](https://user-images.githubusercontent.com/72438169/160524337-c4f6b615-da0f-48ee-a89f-700420d2e2df.png)
![image](https://user-images.githubusercontent.com/72438169/160524597-3adf1d0a-f7f3-4bbd-9b2f-085e212ff48b.png)

**ISSUE 02**
**Describe the bug**
- [x] Text is displayed improperly

**To Reproduce**
1. Go to 'https://aura.network/'
2. See error

**Expected behavior**
Text should not displayed 

**Screenshots**
![image](https://user-images.githubusercontent.com/18638737/160372847-2d580663-2c0b-4f6f-933f-08908f717440.png)

**Desktop (please complete the following information):**
 - Browser : Chrome

**ISSUE 03**
**Describe the bug**
- [x] Scrollbar is displayed on Iphone Xr

**To Reproduce**
1. Go to 'https://aura.network/' on mobile
2. See error

**Expected behavior**
Scrollbar is not displayed on Iphone Xr

**Screenshots**
![1](https://user-images.githubusercontent.com/18638737/160373124-24d5ff40-5e79-493e-a49d-6a1d88d98eeb.jpeg)

**Desktop (please complete the following information):**
 - Mobile : Iphone Xr

**ISSUE 04**
**Describe the bug**
- [x] Space is displayed improperly

**To Reproduce**
On Mobile
1. Go to 'https://aura.network/' on mobile
2. Go to "Advisory Board", "Into the INTEROPERABLE future"
3. See error

On Desktop
1. Go to 'https://aura.network/' on desktop
2. Go to "Advisory Board"
3. See error

**Expected behavior**
Space is not displayed much space

**Screenshots**
![image](https://user-images.githubusercontent.com/18638737/160373556-76692d04-a4ff-4e81-9a54-72d0f77bff9d.png)
![image](https://user-images.githubusercontent.com/24869170/160549853-c0cdeea9-e004-4520-baa9-1642472b1bd7.png)
![image](https://user-images.githubusercontent.com/24869170/160619407-deca791d-f70b-445e-bc37-fe6b026614b9.png)
![image](https://user-images.githubusercontent.com/24869170/160619532-e93c88f8-3c02-4c36-b59f-35acacc6c9cf.png)

**Desktop (please complete the following information):**
 - Mobile : Iphone Xr, Samsung S20 Ultra
 - Desktop screen sizes: 1366 x 768 and 1536 x 864

**ISSUE 05**
**Describe the bug**
- [x] An arrow is overriding a text 2

**To Reproduce**
1. Go to 'https://aura.network/' on mobile
3. See error

**Expected behavior**
An arrow is not overriding a text

**Screenshots**
![image](https://user-images.githubusercontent.com/18638737/160373770-0a400020-f3e3-41d8-8e22-6c8d07806cac.png)

**Desktop (please complete the following information):**
 - Mobile : Redmi Note 8 pro

**ISSUE 06**
**Describe the bug**
- [x] A text is not align center

**To Reproduce**
1. Go to 'https://aura.network/' on mobile
3. See error

**Expected behavior**
A text is align center

**Screenshots**
![image](https://user-images.githubusercontent.com/18638737/160373974-c8f0c993-015d-4b7e-a2ea-a3cba1d9361f.png)

**Desktop (please complete the following information):**
 - Mobile : Redmi Note 8 pro

**ISSUE 07**
**Describe the bug**
- [x] 1/ A text is align improperly
- [x] 2/ Font-size and font-family of dropdown list are incorrect
- [x] 3/ Redundant space under dropdown list

**To Reproduce**
1. Go to 'https://aura.network/' on mobile
2. Click Menu button
5. See error

**Expected behavior**
1/ A text is left-align properly
2/ Font-family: 'Redig', Font-size: 32px
3/ Remove Redundant space

**Screenshots**
![2](https://user-images.githubusercontent.com/18638737/160376461-4034e65e-6503-4c2b-b3db-eedfbb0c79c1.jpeg)
![1 JPG](https://user-images.githubusercontent.com/18638737/160528065-3b798d14-8791-4f3e-9a11-feb0fc1f0274.jpeg)
![image](https://user-images.githubusercontent.com/24869170/160533263-5667e011-8cf9-41d5-be6f-3c0c7b99f192.png)
![image](https://user-images.githubusercontent.com/24869170/160533707-2b53556e-f8e5-4485-bafb-11cf7e6d8861.png)

**Desktop (please complete the following information):**
 - Mobile : Redmi Note 8 pro

**ISSUE 08**
**Describe the bug**
- [x] 1/ Text is break line improperly
- [x] 2/ Display incorrect font-size
- [x] 3/ Redundant space between Icon line and "Copyright © 2022 Aura Network. All rights reserved" text
- [x] 4/ Should remove "Search" input

**To Reproduce**
1. Go to 'https://aura.network/' on mobile
2. Go to the bottom screen

**Expected behavior**
1/ Text is break line properly as figma
2/ Font-size is 16px
3/ Remove redundant space
4/ Remove "Search" input

**Screenshots**
![image](https://user-images.githubusercontent.com/24869170/160597508-23b7321e-0b63-4d0d-87c9-60f2327bbb73.png)

**Desktop (please complete the following information):**
 - Mobile : Iphone XR, Samsung S20 Ultra
 
**ISSUE 09**
**Describe the bug**
- [x] 1/ Display incorrect position of  Headquarter and Footer
- [x] 2/ Display incorrect font-size and font-family of text "Headquarter"
- [x] 3/ Display incorrect font-size of address text at "Headquarter"
- [x] 4/ Display incorrect font-size and font-family of text "Built on Cosmos, powerful for developers"

**To Reproduce**
1. Go to 'https://aura.network/' on mobile
2. Go to Crafting path, Headquarter and Footer

**Expected behavior**
1/ Display correct position of  Headquarter and Footer same as Figma designed
2/ Display correct text "Headquarter": font-size is 16px and font-family is "SF Pro Display"
3/ Display correct text of address at "Headquarter": font-size is 14px
4/ Display correct text "Built on Cosmos, powerful for developers": font-size is 26px and font-family is "SF Pro Display"

**Screenshots**
1/ ![image](https://user-images.githubusercontent.com/24869170/160608679-3aca410d-23fe-460c-a71b-eccbd0698c32.png)
2/ ![image](https://user-images.githubusercontent.com/24869170/160751917-b36ef16b-bc5c-4995-88f0-9878210f4671.png)
3/ ![image](https://user-images.githubusercontent.com/24869170/160609075-7e1100c1-0b8a-4aa5-8594-d9859be1b8a5.png)
4/ ![image](https://user-images.githubusercontent.com/24869170/160609995-7038e96b-e52a-4584-9113-faa5d61b9fb2.png)

 - Mobile : Samsung S20 Ultra

**ISSUE 10**

- [x] Mobile and Desktop: FAQs. khi click show detal question, mũi tên hướng xuống V
      Mobile: Title FAQs căn trái

**Expected behavior**
FAQs. khi click show detal question, mũi tên hướng lên ^
Mobile: Title FAQs căn giữa

![image](https://user-images.githubusercontent.com/72438169/160530236-8a52bc5e-9088-4bfe-ae2e-a745b1d057a7.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/72438169/160517084-eaa7e355-c3f4-494d-b152-b6d849c333a4.png)
![image](https://user-images.githubusercontent.com/72438169/160517203-f41cd836-da79-4761-8ae4-5a8a74e94f52.png)

**ISSUE 11**
**Describe the bug**

- [x] Space of margin  is improperly

**To Reproduce**
1. Go to 'https://aura.network/'
2. See error

**Expected behavior**
Space of margin is as figma
![2](https://user-images.githubusercontent.com/18638737/160521718-23d10077-ce69-422a-bfec-add618c9dcdb.JPG)
![4](https://user-images.githubusercontent.com/18638737/160792359-dab52f6c-40b8-4a40-b71b-617d22573fc0.png)

**Screenshots**
![1](https://user-images.githubusercontent.com/18638737/160521736-61451562-c0b5-4bea-b89b-fbc79a1b3221.JPG)

**Desktop (please complete the following information):**
 - Browser : Chrome

**ISSUE 12**
**Describe the bug**

- [x] Space between multi frames is improperly

**To Reproduce**
1. Go to 'https://aura.network/'
2. See error

**Expected behavior**
Space between multi frames is as figma
![4](https://user-images.githubusercontent.com/18638737/160522784-49e378d2-1bf3-48b1-862e-002f716090f5.JPG)

**Screenshots**
![3](https://user-images.githubusercontent.com/18638737/160522910-c19d7f69-9813-4729-97dd-ff16201907c3.JPG)

**Desktop (please complete the following information):**
 - Browser : Chrome

**ISSUE 13**
**Describe the bug**

- [x] Arrow icon is not displayed on Android

**To Reproduce**
1. Go to 'https://aura.network/' on Android
2. See error

**Expected behavior**
Arrow icon is displayed on Android
![2](https://user-images.githubusercontent.com/18638737/160530784-650e39d7-2375-4746-a48e-e82bc2665f57.jpeg)

**Screenshots**
![1](https://user-images.githubusercontent.com/18638737/160530777-4a5683b5-f483-4470-af4d-44c9e1d901ac.JPEG)

**Desktop (please complete the following information):**
 - Device: Oppo A91

**ISSUE 14**
**Describe the bug**

- [x] 1/ Menu icon (=) is displayed incorrect size
- [x] 2/ Closed icon (X) is displayed incorrect size

**To Reproduce**
1. Go to 'https://aura.network/' on Mobile
2. Click on Menu button
6. See error

**Expected behavior**
1/ Size of Menu icon (=) same as design
2/ Size of Closed icon (X) same as design 18.67 x 18.67

**Screenshots**
![image](https://user-images.githubusercontent.com/24869170/160529897-3d18ed43-f7ef-4c03-a43c-cd6709fe4f16.png)
![image](https://user-images.githubusercontent.com/24869170/160534979-072e2af6-34a3-4fc4-86f7-a26b152149fc.png)

**Desktop (please complete the following information):**
 - Browser : Chrome

**ISSUE 15**
**Describe the bug**

- [x] Should remove "Go to the top screen" button

**To Reproduce**
1. Go to 'https://aura.network/' on Mobile (Samsung S20 Ultra)
2. Click on Menu button
5. See error

**Actual behavior**
Display Go to the top screen (^) button
Click on (^) button, the screen display incorrectly

**Expected behavior**
Remove Go to the top screen (^) button

**Screenshots**
![image](https://user-images.githubusercontent.com/24869170/160530804-842faa3d-1b53-42dd-ae72-08b15662cfb0.png)

**Desktop (please complete the following information):**
 - Browser : Chrome

**ISSUE 16**
**Describe the bug**
- [x] Mobile & Desktop: Update format of list content ROADMAP

**Expected behavior**
![image](https://user-images.githubusercontent.com/72438169/160547493-ab444e6a-70d6-4303-81a2-e98d02aa29f7.png)
![image](https://user-images.githubusercontent.com/72438169/160547637-afa9852c-1d31-489f-a033-662fcd9522af.png)

**ISSUE 17**
**Describe the bug**

- [x] Display wrong position of image

**To Reproduce**
1. Go to 'https://aura.network/' on Mobile (Samsung S20 Ultra)
2. See error

**Expected behavior**
Display correct position of image same as designed

**Screenshots**
![image](https://user-images.githubusercontent.com/24869170/160556077-fa031e8c-e4d1-4e23-92fa-a33dcd071250.png)

 - Browser : Chrome
 - Device: Samsung S20 Ultra

**ISSUE 18**
**Describe the bug**

- [x] Padding of "ROADMAP" image is incorrect on different screen sizes

**To Reproduce**
1. Go to 'https://aura.network/' on Mobile
2. See error

**Expected behavior**
Padding of "ROADMAP" image is correct (16px)

**Screenshots**
![image](https://user-images.githubusercontent.com/24869170/160560512-fec67cdc-1d61-4e8d-93bf-cf0d3e5773f3.png)

 - Browser : Chrome
 - Device: Samsung S20 Ultra, Samsung S10+, Iphone XR

**ISSUE 19**
**Describe the bug**

- [x] Display incorrect background image
- [x] Display incorrect position of icons

**To Reproduce**
1. Go to 'https://aura.network/' on Mobile
2. Go to "Advisory board"
3. Go to "Our Team"
7. See error

**Expected behavior**
At "Advisory board" and "Our Team": Display correct position of icons: Linkin, Twitter
At "Our Team": Remove background image

**Screenshots**
![image](https://user-images.githubusercontent.com/24869170/160571279-6d1530ab-5981-4c43-833e-529801d79765.png)
![image](https://user-images.githubusercontent.com/24869170/160571518-f1c2c67b-ad71-4705-8d89-a9e1da9d228d.png)

 - Browser : Chrome
 - Device: Samsung S20 Ultra

**ISSUE 20**
**Describe the bug**

- [x] Frame of description content is displayed larger than design

**To Reproduce**
1. Go to 'https://aura.network/' on Mobile
2. See error

**Expected behavior**
Frame of description content is displayed as figma
![2](https://user-images.githubusercontent.com/18638737/160574494-7235675e-81f4-4a32-86c6-8263748b82f3.JPG)
![3](https://user-images.githubusercontent.com/18638737/160587139-9f35249c-64f7-4a55-bea3-ad69b4e02cbd.JPG)
![image](https://user-images.githubusercontent.com/18638737/160743263-cfe2dbac-daa1-4b1d-8936-345095dd27b3.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/18638737/160574226-a838b51a-c35f-48c8-aa56-e49427d0ad42.png)

 - Device: Iphone XR

**ISSUE 21**
**Describe the bug**

- [x] 1/ Hiển thị dư 1 phần frame bên phải màn hình
- [x] 2/ Khoảng cách . . .  bị xa

**To Reproduce**
1. Go to 'https://aura.network/' on Mobile
2. Go to "Crafting path"
3. See error

**Expected behavior**
1/ Xóa phần hiển thị dư
2/ Khoảng cách hiện thị . . . giống figma

**Screenshots**
![image](https://user-images.githubusercontent.com/24869170/160736081-fc48ec73-f3d3-448a-aed3-6fe2ec5bc6bb.png)

 - Browser : Chrome
 - Device: Samsung S20 Ultra
 
**ISSUE 22**
**Describe the bug**

- [x] Mobile & Desktop: Update Button Back về đầu trang update theo thiết kế.
- [x] Mobile: Khi ở giữa hoặc cuối trang, click vào nút Back để lên đầu trang -> nút chuyển thành màu hồng khi hover/ click vào -> click xong chuyển lên đầu trang thì nút đó về lại màu xám.

**Expected behavior**
![image](https://user-images.githubusercontent.com/72438169/160740623-2ab1ccd0-c3a6-445e-80f7-47df6ce0806f.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/72438169/160740942-3c4de9f4-58d3-452e-b4a3-1e2f9584fd30.png)
![image](https://user-images.githubusercontent.com/72438169/160768474-4f5a0892-464e-49dc-a267-74a7a2d114d6.png)

**ISSUE 23**
Describe the bug

- [x] 1/ Display incorrect font-size and font-family of text "Let 's talk"
- [x] 2/ Display incorrect font-size and font-family of text "Founder"
- [x] 3/ Display incorrect font-size and font-family of text "A diversified team of blockchain believers"

Steps 
1. Go to 'https://aura.network/' on web ( screen: 1512 x 850 px )
2. Go to Crafting path, Headquarter and Footer
3. See error

Image:
1/
![image](https://user-images.githubusercontent.com/18638737/160752127-3d5a900c-d722-4c59-8dd5-c14b0853de66.png)
2/
![1](https://user-images.githubusercontent.com/18638737/160752612-381bff19-4d0b-47b1-8a37-829f7c8c117b.JPG)
![3](https://user-images.githubusercontent.com/18638737/160753331-f727b182-09cf-452f-83df-c135fc51dab2.JPG)
3/
![1](https://user-images.githubusercontent.com/18638737/160753154-d3530c02-fc6d-4278-bbc8-db3ca63d0ede.JPG)
![4](https://user-images.githubusercontent.com/18638737/160753463-97e39798-e750-49d8-a3d2-e98a33900982.JPG)

Expected behavior
1/ Display incorrect font-size and font-family of text "Let 's talk" ( 16 px )
![2](https://user-images.githubusercontent.com/18638737/160752065-4453ed7b-8f5a-4e19-9fbb-5e49d37cbf6a.JPG)

2/ Display incorrect font-size and font-family of text "Founder" ( 14 px )
![2](https://user-images.githubusercontent.com/18638737/160752634-104d971e-11d3-481a-85b9-d1819f1c4676.JPG)

3/ Display incorrect font-size and font-family of text "A diversified team of blockchain believers" ( 24px)
![2](https://user-images.githubusercontent.com/18638737/160753122-dcc96330-8092-415e-b902-5ce558cce7c8.JPG)

**ISSUE 24**
Describe the bug

- [x] 1/ Display incorrect line-height
- [x] 2/ Space between lines should be 16px
- [x] 3/ Space between item of menu should be as figma ( 72 px )

Steps 

1. Go to 'https://aura.network/' on web ( screen: 1512 x 850 px )
2. See error

Expected behavior
1/ Display incorrect line-height ( 40 px ) and letter-spacing is 2 px
![2](https://user-images.githubusercontent.com/18638737/160767069-c37244e4-27a3-42be-94f3-7ab79f2c1c34.JPG)
![2](https://user-images.githubusercontent.com/18638737/160769619-caa0a87a-622c-45db-89ba-3b55fae5f8af.JPG)

2/ Space between lines should be 16px
![3](https://user-images.githubusercontent.com/18638737/160768271-3bb763ae-23ed-45d1-ab90-2c8861a0fc4d.png)

3/ Space between item of menu should be as figma ( 72 px )
![2](https://user-images.githubusercontent.com/18638737/160772884-b91e9fad-e2d9-49eb-bfc4-e206c1fb193a.png)

Screenshots
![1](https://user-images.githubusercontent.com/18638737/160767465-6d018cd7-7b5b-460b-b313-fa1a320e17db.JPG)
![1](https://user-images.githubusercontent.com/18638737/160769714-5eabd6f1-ace5-47b1-aef5-dbb68f60d440.JPG)
![1](https://user-images.githubusercontent.com/18638737/160772848-e10e9c56-289b-49ef-b52a-32f8b7f7de64.png)

**ISSUE 25**
Describe the bug

- [ ] Community button on header disappears after it is clicked
- [ ] Community button on footer disappears after it is clicked
Steps 

1. Go to 'https://aura.network/' on Redmi Note 8 pro
2. Click on Community button

Expected behavior
Community button reappears after it is clicked
Screenshots

![image](https://user-images.githubusercontent.com/102127509/160786556-dc317f66-b78e-49ac-a9fd-4c629612cc2a.png)
![image](https://user-images.githubusercontent.com/102127509/160786602-4055f76e-59c3-45ac-9885-0baee3023908.png)

**ISSUE 26**
Describe the bug

- [ ] At the firt time, Community buttons on header disappear until the user crolls to the bottom of the page
Steps 

1. Go to 'https://aura.network/' on Redmi Note 8 pro
2. Click on "=" icon
Expected behavior
Community buttons are display
Screenshots
![image](https://user-images.githubusercontent.com/102127509/160796973-aa73b51f-6555-4420-96dc-86a441d3dbf9.png)

**ISSUE 27**
Describe the bug

- [x] Image does not stay a right position 

Steps 
1. Go to 'https://aura.network/' on web ( screen: 1512 px x 1133 px )

Expected behavior
Image  stays a right position 
![image](https://user-images.githubusercontent.com/18638737/160803268-d65a49c1-ae04-469f-9c1d-9336a389777a.png)

Screenshots
![1](https://user-images.githubusercontent.com/18638737/160803313-75c413e1-a29a-420a-a6d9-1d9f5bd4ed99.JPG)

**Comment by Dpthao245** [comment]
**ISSUE 01**
Describe the bug
- [ ] Mobile & Desktop: Chỉnh màu title 11/2021, Q1-2022, Q2-2022, ....

**Screenshots**
![image](https://user-images.githubusercontent.com/72438169/160766430-0599787c-252d-4aea-9cb4-9b12ab570ea3.png)

**ISSUE 02**
- [ ] Mobile & Desktop: Chỉnh font chữ "Let's talk"

**Screenshots**
![image](https://user-images.githubusercontent.com/72438169/160766657-99a12c05-f8e6-4640-8353-ecce51da1451.png)

**Comment by BichPTN1** [comment]
ISSUE 5: PASS
![image](https://user-images.githubusercontent.com/102127509/160969676-27cbe2e6-6535-4b8a-8573-c7b4d332421b.png)
ISSUE 6: PASS
![image](https://user-images.githubusercontent.com/102127509/160969795-98b0b6d8-9caa-4eaf-b50d-95a1de616618.png)
![image](https://user-images.githubusercontent.com/102127509/160969802-73cd8d3c-d00a-4e63-a387-df043ad540fa.png)

**Comment by vitrantuong** [comment]
Verify pass issue 2, 3, 12, 20, 23, 24
![issue2](https://user-images.githubusercontent.com/18638737/160972995-abaa1650-e5d6-4f59-a956-db6d9a6279b6.JPG)
![issue3](https://user-images.githubusercontent.com/18638737/160973010-482d3ab1-1cda-4ec3-a941-c89bb4517798.jpeg)
![issue12](https://user-images.githubusercontent.com/18638737/160973011-f79b5207-17c1-4800-b5ec-d57a788b82ed.JPG)
![issue20](https://user-images.githubusercontent.com/18638737/160973013-762011a8-6c69-4030-9e69-e11e6d9205b2.jpeg)
![issue20_1](https://user-images.githubusercontent.com/18638737/160973015-fb9559cd-2217-417c-88b0-8fd6a2617b37.jpeg)
![issue23](https://user-images.githubusercontent.com/18638737/160973016-72f0dc01-f508-4cfb-a73a-8697a2a3d77a.png)
![issue23_1](https://user-images.githubusercontent.com/18638737/160973018-53ff4991-c5bc-418e-8f38-afcd27be967b.png)
![issue23_2](https://user-images.githubusercontent.com/18638737/160973020-0ee1479f-2de6-4b85-ad8b-ee5e27c6c6e2.png)
![issue24](https://user-images.githubusercontent.com/18638737/160973023-b91067bd-f0c3-4311-9f2f-bc6426b4be1c.JPG)
![issue24_1](https://user-images.githubusercontent.com/18638737/160973024-1eb1b7f9-9d07-4493-8c05-8cde846e6d98.png)
![issue24_2](https://user-images.githubusercontent.com/18638737/160973028-c7f36b21-4ae9-422a-9716-df973dd29e90.JPG)

**Comment by ntatfff** [comment]
Verify on link https://aura.network/ (31/03/2022)
**FAIL issues:**
**ISSUE 04:**
- chưa cắt hình chỗ phi hành gia
- Chưa xóa khoảng trống và di chuyển ngôi sao nhỏ xuống dưới chỗ Our Team trên desktop
- Xuất hiện thêm khoảng trống dư thừa ở dưới Roadmap

**ISSUE 07:**
3/ chưa xóa Redundant space
4/ chưa chỉnh IN HOA của dropdown list

**ISSUE 17:**
Hiển thị hình chưa đúng vị trí
![image](https://user-images.githubusercontent.com/24869170/160970700-9b630703-62d0-41d3-be5a-a8a9008730ba.png)

**ISSUE 18:**
ROADMAP image đã canh giữa, nhưng chưa hiện full (cách lề 2 bên 16px)
![image](https://user-images.githubusercontent.com/24869170/160973100-d4b686fc-5b0b-42cf-b065-1bff820d9dde.png)

**ISSUE 19:**
Hiển thị thứ tự icons đúng
Chưa xóa background image
![image](https://user-images.githubusercontent.com/24869170/160973856-82c9f78b-577d-49c3-a32e-c1d4b067c40e.png)

**ISSUE 21:**
Chưa fix được
![image](https://user-images.githubusercontent.com/24869170/160974155-8a6e6320-dfce-44f4-8c94-6eeb3f807c12.png)

**PASS issues:** ISSUE 09, 14, 15,

**Comment by vitrantuong** [comment]
Verify pass issue 27
![issue27](https://user-images.githubusercontent.com/18638737/161014830-36e7ea1e-d0b9-47e9-95b6-0f97aa4b3088.JPG)

**Comment by ntatfff** [comment]
Verify on link https://aura.network/ (31/03/2022 15:30)
PASS issues:
ISSUE 04: PASS
![image](https://user-images.githubusercontent.com/24869170/161016804-30fb263d-6a9c-47a7-97e9-e628be0192e6.png)
![image](https://user-images.githubusercontent.com/24869170/161017086-495009c6-426c-4b9b-9007-897c3d5e3c16.png)

ISSUE 07: PASS
Chữ in thường sẽ dễ nhìn hơn
![image](https://user-images.githubusercontent.com/24869170/161018791-97f7b94b-3f0b-4ff9-922c-e355f6a65e13.png)

ISSUE 17: PASS => không cần chỉnh thêm

ISSUE 19: PASS
![image](https://user-images.githubusercontent.com/24869170/161019277-5b34e58c-ee9d-4701-b7ea-a906aa7b53ac.png)

ISSUE 21: PASS
![image](https://user-images.githubusercontent.com/24869170/161019397-f0bdec7a-2547-40a3-9bd3-e0ca0b651a20.png)

**Comment by vitrantuong** [comment]
Verify pass issue 06 and failed issue 22
![issue6](https://user-images.githubusercontent.com/18638737/161022463-9e25c26f-7fcf-446c-b759-db83da635f3a.png)

**Comment by vitrantuong** [comment]
Close this issue
