### ISSUE TITLE
[Aura Insights] Remove banner in post

### ISSUE THREAD

**Issue by thinhnguyenplus** [aura-nw/landing-page#127]
Hiện tại trong bài viết của trang insights đang có 1 vấn đề là hình ảnh đang xuất hiện trùng lặp.

Đây không phải lỗi mà là tính năng của wp khi lựa chọn ảnh thumnail. Nhưng khi nếu xoá bỏ ảnh thumnail thì khi preview trên trang chủ sẽ trống trơn.

Vậy mình đề xuất là trong khi edit post vẫn chọn được ảnh thumnail. Nhưng khi public lên thì chỉ hiện ảnh trong bài viết. Không hiển thị trên banner nữa. Và khi click về trang chủ vẫn có ảnh thumpnail như bình thường.

![image](https://user-images.githubusercontent.com/8298102/160963973-6baa10c0-9ba9-4b02-99f3-b6afbe44555c.png)

**Comment by letrieuthien** [comment]
Đã thêm 1 option Show Feature Image as Banner phía bên dưới bài viết, giờ đây admin check vào mục này thì hệ thống sẽ ko lấy ảnh feature image set làm banner cho bài chi tiết
![image](https://user-images.githubusercontent.com/40551377/160983374-f682e07d-e7b1-4c5a-a160-8528dc823354.png)
