### ISSUE TITLE
[AuraNews] Some issues of Aura News/Insight

### ISSUE THREAD

**Issue by hangpham23** [aura-nw/landing-page#132]
**According to Figma design since 14:10 31/3/2022**
https://www.figma.com/file/u9FVvZYiA6pTpoZYqmHpf1/AuraNetwork---Landingpage?node-id=1946%3A9953

**To Reproduce**
1. Go to https://insight.aura.network/

**List issues**

**ISSUE 01:**
- [x] Vị trí của list categories đang ở lề trái 

**Expected behavior**
List categories chuyển về center
![image](https://user-images.githubusercontent.com/72438169/161003664-3c4b56e6-db3f-4ef1-80a6-1db7c47039c3.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/72438169/161003543-29d4411d-39ba-4e26-b314-2145a78de508.png)

**ISSUE 02:**
- [x] Bỏ content "Welcome to Aura Insights" ở banner

**Expected behavior**
banner hiển thị theo design Figma

**Screenshots**
<img width="1440" alt="Screen Shot 2022-03-31 at 14 19 44" src="https://user-images.githubusercontent.com/102220123/161001435-7f1f103e-b845-4890-8134-cf64899ddf2f.png">

**ISSUE 03:**
- [x] 3. Thiếu social icon trên header và footer cũng như ở Follow Us On. icon hiển thị lỗi 
![image_2022_03_31T08_12_07_201Z](https://user-images.githubusercontent.com/102220123/161010929-160d534f-1273-4235-bf78-55280b1d76e7.png)

**Expected behavior**
Hiển thị đủ và đúng social icon như design
<img width="785" alt="Screen Shot 2022-03-31 at 14 53 36" src="https://user-images.githubusercontent.com/102220123/161005848-9f6862f6-13bd-47f3-afa7-6f39560b07dd.png">
<img width="786" alt="Screen Shot 2022-03-31 at 14 53 53" src="https://user-images.githubusercontent.com/102220123/161005856-b661868f-31d5-4b64-b837-a88cea153252.png">
<img width="286" alt="Screen Shot 2022-03-31 at 14 54 05" src="https://user-images.githubusercontent.com/102220123/161005859-1e73bc5d-6ef3-40d3-bb67-92dfc2e6619b.png">

**Screenshots**

**ISSUE 04:**
- [x] Bài post chưa có text link See more

**Expected behavior**
Click See more -> Insights Post Details
![image](https://user-images.githubusercontent.com/72438169/161000693-f08f2ba5-047e-4e07-b808-266ae4c7fbfc.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/72438169/161000767-bf832577-5e5c-43ff-b740-2ece02dbea8c.png)

**ISSUE 05**
- [x] Social icon ở bài post/Share post chưa có hover animation

**Expected behavior**
Social icon ở Post/Share post hiển thị animation khi hover
<img width="411" alt="Screen Shot 2022-03-31 at 10 33 00" src="https://user-images.githubusercontent.com/102220123/161001823-ec3e9fce-8df5-4a62-b28f-b461fd4abbf0.png">

**Screenshots**

<img width="348" alt="Screen Shot 2022-03-31 at 10 30 54" src="https://user-images.githubusercontent.com/102220123/161001878-b8d41d76-da26-457d-a9d1-8946bd34dc49.png">

**Desktop (please complete the following information):**

**Additional context**

**Comment by Dpthao245** [comment]
**According to Figma design since 14:10 31/3/2022**
https://www.figma.com/file/u9FVvZYiA6pTpoZYqmHpf1/AuraNetwork---Landingpage?node-id=1946%3A9953

**To Reproduce**
Steps to reproduce the behavior:
1. Go to https://insight.aura.network/

**List issues**

**ISSUE 01:**
- [ ] Footer: Home không click được

**Expected behavior**
Footer Home khi click vào -> Xử lý giống Header Home

**Screenshots**
![image](https://user-images.githubusercontent.com/72438169/161001070-5ec22c64-6643-4633-9601-1df31901cf9f.png)

**Comment by letrieuthien** [comment]
Issue 04: Bài post chưa có text link See more
-------
Dev note: Không thể làm chữ "see more" cùng hàng như vậy được, chỉ có thể cho xuống hàng
