### ISSUE TITLE
[LandingPage] Update layout according to grid

### ISSUE THREAD

**Issue by NgocAnh7278** [aura-nw/landing-page#133]
Link des: https://www.figma.com/file/u9FVvZYiA6pTpoZYqmHpf1/AuraNetwork---Landingpage?node-id=0%3A1
----------
Update lại giao diện nằm trong grid layout

- [x] Section hero banner
- [x]  Section Introduction
- [x]  Section Outstanding Feature
- [x]  Section partner (Phần này ko ưu tiên/ làm sau cùng)
- [x] Section roadmap
- [x] Section advisory
- [x] Section team
- [x] Section faq

**Comment by NgocAnh7278** [comment]
01/04/2022: Ngoc Anh BA updates:
- [ ] Footer: Bỏ địa chỉ Headquarter:
![image](https://user-images.githubusercontent.com/40628286/161183947-5842a963-6104-4f53-a0cd-349ba3499036.png)

- [ ] Update thumbnail landing page
![image](https://user-images.githubusercontent.com/40628286/161184013-25f402fa-b750-402b-ad64-e014ac7810f2.png)
_Link des Update_:
https://www.figma.com/file/u9FVvZYiA6pTpoZYqmHpf1/AuraNetwork---Landingpage?node-id=1742%3A7660

**Comment by vitrantuong** [comment]
Verify pass issue 1, 2, 3 on 
![image](https://user-images.githubusercontent.com/18638737/161715298-24609b06-7734-47ea-80e2-1a019da43db1.png)
![image](https://user-images.githubusercontent.com/18638737/161718008-e6116785-b94b-465f-aa03-36f8972e7e68.png)
![image](https://user-images.githubusercontent.com/18638737/161718180-f0d6d458-2672-4888-9aaa-0a4bb7754ad9.png)
![image](https://user-images.githubusercontent.com/18638737/161714991-7e2599e3-724f-4b6b-ad5e-e88e2369119c.png)

**Comment by vitrantuong** [comment]
Verify pass issue 3
![image](https://user-images.githubusercontent.com/18638737/161951625-5ff54f7b-40d8-41c6-ad6d-c295a7e14dcf.png)
