### ISSUE TITLE
[Landing Page] Some issue on Landing page 2 ( Narrow, wide screen on mobile phone )

### ISSUE THREAD

**Issue by vitrantuong** [aura-nw/landing-page#135]
**ISSUE 01**
Describe the bug

- [x] Text should not be limit a height because text is not displayed fully

Steps 
1. Go to 'https://aura.network/' on mobile

Expected behavior
Change as https://github.com/aura-nw/landing-page/issues/64#issuecomment-1085350694

Screenshot:
![1](https://user-images.githubusercontent.com/18638737/161004867-d1a22e7a-ee31-4470-a399-4f4d3339c188.JPG)
![2](https://user-images.githubusercontent.com/18638737/161005489-10ae6a43-dacb-4345-a347-dbc4328414fc.JPG)

Device: Oppo A91

**ISSUE 02**
**Describe the bug**

- [x] Mobile & Desktop: Update Button Back về đầu trang update theo thiết kế.
- [x] Mobile: Khi ở giữa hoặc cuối trang, click vào nút Back để lên đầu trang -> nút chuyển thành màu hồng khi hover/ click vào -> click xong chuyển lên đầu trang thì nút đó về lại màu xám.

**Expected behavior**
![image](https://user-images.githubusercontent.com/72438169/160740623-2ab1ccd0-c3a6-445e-80f7-47df6ce0806f.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/72438169/160740942-3c4de9f4-58d3-452e-b4a3-1e2f9584fd30.png)
![image](https://user-images.githubusercontent.com/72438169/160768474-4f5a0892-464e-49dc-a267-74a7a2d114d6.png)

**ISSUE 03**
**Describe the bug**

- [x] Arrow icon is not displayed on Android

**To Reproduce**
1. Go to 'https://aura.network/' on Android
2. See error

**Expected behavior**
Arrow icon is displayed on Android
![2](https://user-images.githubusercontent.com/18638737/160530784-650e39d7-2375-4746-a48e-e82bc2665f57.jpeg)

**Screenshots**
![1](https://user-images.githubusercontent.com/18638737/160530777-4a5683b5-f483-4470-af4d-44c9e1d901ac.JPEG)

**Desktop (please complete the following information):**
 - Device: Oppo A91

**ISSUE 04**
**Describe the bug**

- [x] Space of margin  is improperly

**To Reproduce**
1. Go to 'https://aura.network/'
2. See error

**Expected behavior**
Space of margin is as figma
![2](https://user-images.githubusercontent.com/18638737/160521718-23d10077-ce69-422a-bfec-add618c9dcdb.JPG)
![4](https://user-images.githubusercontent.com/18638737/160792359-dab52f6c-40b8-4a40-b71b-617d22573fc0.png)

**Screenshots**
![1](https://user-images.githubusercontent.com/18638737/160521736-61451562-c0b5-4bea-b89b-fbc79a1b3221.JPG)

**Desktop (please complete the following information):**
 - Browser : Chrome

**ISSUE 05**
**Describe the bug**

- [x] Update displaying information at "Let's talk!"

**To Reproduce**
1. Go to 'https://aura.network/' on Mobile and Desktop
2. Go to "Let's talk!"
3. See error

**Expected behavior**
Update same as Figma designed

**Screenshots**
![image](https://user-images.githubusercontent.com/24869170/161035189-42da940a-470b-42f8-85a5-193b806f52c8.png)
![image](https://user-images.githubusercontent.com/24869170/161035525-18d7c7f5-fb0e-4778-89ab-cb829cc6bc7d.png)

- Device: Mobile and Desktop
 - Browser : Chrome

ISSUE 6
Describe the bug

 

- [x] Community button on header disappears after it is clicked

- [x] Community button on footer disappears after it is clicked

Steps

1. Go to 'https://aura.network/' on Redmi Note 8 pro
2. Click on Community button

Expected behavior
Community button reappears after it is clicked
Screenshots
![image](https://user-images.githubusercontent.com/102127509/160786556-dc317f66-b78e-49ac-a9fd-4c629612cc2a.png)
![image](https://user-images.githubusercontent.com/102127509/160786602-4055f76e-59c3-45ac-9885-0baee3023908.png)

ISSUE 7
Describe the bug

- [x]  At the firt time, Community buttons on header disappear until the user crolls to the bottom of the page

Steps
1. Go to 'https://aura.network/' on Redmi Note 8 pro
2. Click on "=" icon
Expected behavior
Community buttons are display

Screenshots
![image](https://user-images.githubusercontent.com/102127509/160796973-aa73b51f-6555-4420-96dc-86a441d3dbf9.png)

**ISSUE 08**

Describe the bug

- [x] Text is not displayed fully

Steps 
1. Go to 'https://aura.network/' on mobile ( screen: 1809px)
2. See error

Expected behavior
Text is displayed fully

Screenshot:
![1](https://user-images.githubusercontent.com/18638737/161186883-47d01693-fa2d-45a2-97a2-c20e93b75d55.JPG)

Device: Oppo A91 

**ISSUE 09**

Describe the bug

- [x] Logo Aura in footer grid is missing

Steps 
1. Go to 'https://aura.network/' on mobile 
2. See error
Expected behavior
Logo is display as design 

Screenshot:
![11](https://user-images.githubusercontent.com/102220123/161522436-b0ce9554-1ab8-4785-bb98-d130d91d5e37.jpg)

<img width="267" alt="Screen Shot 2022-04-04 at 17 06 18" src="https://user-images.githubusercontent.com/102220123/161522460-795ff65f-6f5a-4da7-9a95-c7411b808d29.png">

Device: ip 11 pro max

**Comment by ntatfff** [comment]
Verified on https://dev.aura.network/ (17h 05-Apr-2022)
- FAIL issues: 02, 05, 08
- PASS issues: 01, 03, 04, 06, 09
- Has not fixed issue yet: 07

ISSUE 01: PASS
![image](https://user-images.githubusercontent.com/24869170/161734254-e2dda9ac-d66f-4722-b2c1-738429da8b57.png)

ISSUE 02: FAIL on Mobile - Chưa chuyển nút mũi tên màu xám ở lần hiển thị thứ 2 trở đi
![image](https://user-images.githubusercontent.com/24869170/161734508-472cf696-2520-46bf-8f30-87c65d934758.png)

ISSUE 03: PASS
![image](https://user-images.githubusercontent.com/24869170/161734953-26752591-a1c4-408c-b13b-9925598c6198.png)

ISSUE 04: PASS
![image](https://user-images.githubusercontent.com/24869170/161735103-f4888cd9-ad81-4fbe-a9d6-2efb52c6eb63.png)

ISSUE 05: FAIL on Mobile - Khung bị lệch sang trái
**Expected result:** Canh giữa khung  "LET'S TALK!"
![image](https://user-images.githubusercontent.com/24869170/161736092-582244c2-5258-47b6-bdb7-3ef7ee430da0.png)

ISSUE 06: PASS
![image](https://user-images.githubusercontent.com/24869170/161736726-a0062ea1-f088-4251-a2ac-de10636a265f.png)

ISSUE 07: chưa xử lý

ISSUE 08: FAIL on Desktop - Hiện nút mũi tên che mất chữ
![image](https://user-images.githubusercontent.com/24869170/161736959-a8ede0e8-b0b8-4a04-9819-819418742d18.png)

ISSUE 09: PASS
![image](https://user-images.githubusercontent.com/24869170/161737089-903fa78a-b153-46fd-a533-d88f0cdf3e52.png)

**Comment by BichPTN1** [comment]
Verified on https://dev.aura.network/ (06-Apr-2022)

PASS issues: 07

**Comment by ntatfff** [comment]
Verified on https://aura.network/ and https://dev.aura.network/ (17h 06-Apr-2022)
PASS issues: 02, 05, 08

ISSUE 02: PASS
![image](https://user-images.githubusercontent.com/24869170/161955878-e59754f9-14ed-4115-8aad-05f037fd1063.png)

ISSUE 05: PASS
![image](https://user-images.githubusercontent.com/24869170/161958300-1fedff79-732d-43e0-b760-793ea34e3797.png)

ISSUE 08: PASS
![image](https://user-images.githubusercontent.com/24869170/161958441-7303f00f-825a-4d1f-840d-384b40a02f77.png)
