### ISSUE TITLE
Add contract address and How to buy Aura

### ISSUE THREAD

**Issue by NgocAnh7278** [aura-nw/landing-page#262]
- [x] Move button Whitepaper
![image](https://user-images.githubusercontent.com/40628286/182547764-a781d118-a223-4432-8727-a4e85ed98dc8.png)

- [x] Add button Buy now. Click button -> show popup How to buy Aura
- [x] Add Aura contract on Binance Smart Chain
Link figma: https://www.figma.com/file/u9FVvZYiA6pTpoZYqmHpf1/AuraNetwork---Landingpage?node-id=10653%3A23495
Link notion specification: https://www.notion.so/aura-network/Add-Aura-smart-contract-on-BSC-and-Buy-now-on-IF-Baryon-bf71d90811d34b40bb7ad67805750c1b

**Comment by Dpthao245** [comment]
FAIl in Dev 04/08/2022

**Desktop**

- [ ] ISSSUE 01: Button sai màu #FCFCFD -> #FFFFFF
![image](https://user-images.githubusercontent.com/72438169/182780420-073ad594-7b37-4050-9f34-3bd81eeec17a.png)

- [ ] ISSSUE 02: Button sai màu #FCFCFD, 400 -> #FFFFFF, 500
![image](https://user-images.githubusercontent.com/72438169/182780619-fb542b24-d05c-4f99-a604-eeaad2113e86.png)

- [ ] ISSUE 03: Sai màu text 000000 -> Gradient
![image](https://user-images.githubusercontent.com/72438169/182780764-2d870529-d670-4507-91b4-2208d6e7473c.png)

**Mobile** IOS

- [ ] ISSUE 04: Sai màu text
![image](https://user-images.githubusercontent.com/72438169/182781446-d701ea56-2ff2-4d49-b1bc-2a255342afdd.png)

- [ ] ISSUE 05: Sai màu text và không hiển link
![image](https://user-images.githubusercontent.com/72438169/182781201-98c9a442-8879-4697-b250-45a60d9c8805.png)

**Comment by Dpthao245** [comment]
PASS in Dev
ISSUE 01:
![image](https://user-images.githubusercontent.com/72438169/182790561-421a1376-b46d-407a-9cee-db6cfa19acf6.png)

ISSUE 02:
![image](https://user-images.githubusercontent.com/72438169/182790813-60d5cc0c-c7dd-42db-9b1e-314f1a44829c.png)

ISSUE 03:
![image](https://user-images.githubusercontent.com/72438169/182791063-1ec17f01-a6cf-466e-bda1-dd4e7f746f3f.png)
![image](https://user-images.githubusercontent.com/72438169/182791201-6e61d603-89da-48f1-a595-eb3930189bc7.png)

ISSUE 04:
![image](https://user-images.githubusercontent.com/72438169/182791919-5d38d932-af24-4766-b180-af6bad045f99.png)

ISSUE 05:
![image](https://user-images.githubusercontent.com/72438169/182792033-91d151d9-a910-4da4-bfff-d255f59d711d.png)

ISSUE 06:
![image](https://user-images.githubusercontent.com/72438169/182792195-b12523f8-3977-43d5-99c1-eb2802c84438.png)

ISSUE 07:
![image](https://user-images.githubusercontent.com/72438169/182792308-c52eb39a-c325-43e2-8448-29a8afabf8cd.png)
![image](https://user-images.githubusercontent.com/72438169/182792434-3d59c8ae-73b7-4f12-a26c-17105a05f06b.png)

**Comment by Dpthao245** [comment]
PASS in Aura.network
Desktop
![image](https://user-images.githubusercontent.com/72438169/182801367-8d510937-6d80-4d7c-a9c1-a76e672286c1.png)
![image](https://user-images.githubusercontent.com/72438169/182801929-8ed4afe2-e1f3-4632-817f-076d7d841563.png)
![image](https://user-images.githubusercontent.com/72438169/182801467-65525c21-8561-4552-81e4-aef7d5071443.png)
![image](https://user-images.githubusercontent.com/72438169/182801583-d931fb8e-dfe2-4e96-991f-1fcce6ce14f2.png)
![image](https://user-images.githubusercontent.com/72438169/182801669-142e67b6-1ccd-469a-89a6-9a0591b976ba.png)
![image](https://user-images.githubusercontent.com/72438169/182801700-6c0089b7-db9f-4001-861a-c1e1f4f007c6.png)
![image](https://user-images.githubusercontent.com/72438169/182801812-9052f987-f225-43ae-ad52-06bc7fa50223.png)

Mobile
![image](https://user-images.githubusercontent.com/72438169/182802223-c2caaf37-7082-45aa-8390-ac62662ee07e.png)
![image](https://user-images.githubusercontent.com/72438169/182802355-7edfb85f-bacb-4a50-b2b6-3425d77b5849.png)
![image](https://user-images.githubusercontent.com/72438169/182802477-687bacd3-581b-4a02-947a-74ace99fe4b0.png)
![image](https://user-images.githubusercontent.com/72438169/182802591-6fb47ba9-c35d-4e3a-8b53-60b95f88ef2b.png)
