### ISSUE TITLE
Update BNB chain and link swap

### ISSUE THREAD

**Issue by NgocAnh7278** [aura-nw/landing-page#268]
https://www.notion.so/aura-network/Add-Aura-smart-contract-on-BSC-and-Buy-now-on-IF-Baryon-bf71d90811d34b40bb7ad67805750c1b

- [x] add hover animation when Users hover button Baryon and Impossible Finance

**Comment by letrieuthien** [comment]
https://www.figma.com/file/u9FVvZYiA6pTpoZYqmHpf1/AuraNetwork---Landingpage?node-id=10713%3A24191

**Comment by Dpthao245** [comment]
PASS in Aura.network

![image](https://user-images.githubusercontent.com/72438169/182999262-2841564c-c54e-4179-beb0-ad53862421ac.png)
![image](https://user-images.githubusercontent.com/72438169/182999288-a814a7ae-edcc-42dd-bb20-98a1351fc216.png)
![image](https://user-images.githubusercontent.com/72438169/182999302-ca7c07f0-5e78-4677-a3c9-4cc706b20057.png)
![image](https://user-images.githubusercontent.com/72438169/182999435-63aaae81-f143-4022-abfe-1aa58eb2f008.png)
![image](https://user-images.githubusercontent.com/72438169/182999452-e5a31d11-12dd-4c80-af1d-fc17aa5a6e5e.png)
![image](https://user-images.githubusercontent.com/72438169/182999500-90729eb7-6ab9-469d-92a1-8e40f4a397c3.png)
![image](https://user-images.githubusercontent.com/72438169/182999533-0bc14b41-a1fc-4394-ac52-68bd3a8ba9b1.png)
![image](https://user-images.githubusercontent.com/72438169/182999596-9834b1a7-6e6c-49ca-9fdb-0c840478e34f.png)
![image](https://user-images.githubusercontent.com/72438169/182999613-a0ae9c5e-4905-4caf-aaca-1cb1fba26e3e.png)
