### ISSUE TITLE
Add count down mainnet launch & add Centralized exchange

### ISSUE THREAD

**Issue by NgocAnh7278** [aura-nw/landing-page#275]
- [x] Add count down mainnet launch (Aura mainnet launch will start at 01/10/2022 10:10 am)
- [x] Add Centralized exchange in popup Buy now
Mexc: https://www.mexc.com/exchange/AURA_USDT
Bingx: https://bingx.com/en-us/spot/AURAUSDT/
Bitget: _will be updated soon_ (code but don't show, hide until have link)
- [x] Update link: See more details -> click -> open a new tab & view: https://insight.aura.network/tag/listing/
Link figma: https://www.figma.com/file/u9FVvZYiA6pTpoZYqmHpf1/%5BAura%5D-Landingpage?node-id=3880%3A9578

**Comment by NgocAnh7278** [comment]
Add 3 hot news:
- [ ] Aura Farming pool: https://insight.aura.network/tutorial-how-to-farm-aura/
- [ ] Aura Staking pool: https://insight.aura.network/tutorial-how-to-stake-aura/
- [ ] How to get Aura: https://insight.aura.network/full-tutorial-how-to-buy-aura/
Link figma: https://www.figma.com/file/u9FVvZYiA6pTpoZYqmHpf1/%5BAura%5D-Landingpage?node-id=3880%3A9578
![image](https://user-images.githubusercontent.com/40628286/185048775-f3a3e30b-6beb-4db3-94be-7ad2447420cb.png)

**Comment by ntatfff** [comment]
Verified PASS on dev (17/08/2022)
![image](https://user-images.githubusercontent.com/24869170/185098000-5f898271-af6d-410e-af57-d92241ba607f.png)
![image](https://user-images.githubusercontent.com/24869170/185098033-96149a57-9b34-406f-bf9f-d25f6264a34c.png)
![image](https://user-images.githubusercontent.com/24869170/185098068-bbcdab55-ce89-4b4f-8e04-c5299f18dbca.png)
![image](https://user-images.githubusercontent.com/24869170/185098398-d1b8cec3-044d-4442-9ffd-b91c033f6d52.png)
![image](https://user-images.githubusercontent.com/24869170/185098486-dc8e6294-b904-407a-894d-4edca4a0a46d.png)
