### ISSUE TITLE
Change something on Aura landing page from feedback of marketing

### ISSUE THREAD

**Issue by NgocAnh7278** [aura-nw/landing-page#281]
Link feedback and change: https://www.canva.com/design/DAFJp71lhPE/b2p2CEby4AIdDhBW3aFwyQ/edit?utm_content=DAFJp71lhPE&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
Link figma: https://www.figma.com/file/u9FVvZYiA6pTpoZYqmHpf1/%5BAura%5D-Landingpage?node-id=3880%3A9578

**Comment by ntatfff** [comment]
Verified on dev (19/08/2022)
1. PASS: Thay đổi text ở trên count down time -> 'Xstaxy' Mainnet Launch Starting In
2. PASS: Fill màu button BUY NOW
3. PASS: Chuyển  "Mainnet Release" từ Q3 -> Q4
4. PASS: Đổi text từ "Hot News" -> Campaigns Happening Now
5. PASS: Thay đổi thứ tự News
6. PASS: Thay đổi màu viền khung khi hover chuột lên từng news (desktop)

**Chưa thay đổi: chờ có nội dung của các news mới**
7. banner slide hiện tại sẽ có 2 trang. Mỗi trang có 3 bài. 

**Screenshots:**
![image](https://user-images.githubusercontent.com/24869170/185580743-24d24f81-4f82-483d-98ec-220d8d7b9eb9.png)
![image](https://user-images.githubusercontent.com/24869170/185580586-9a549ec3-d3e0-41ab-be2a-c659303cc6ee.png)
![image](https://user-images.githubusercontent.com/24869170/185582922-8e0f4985-8cb0-42cf-ac10-3d9231dd099b.png)
![image](https://user-images.githubusercontent.com/24869170/185582357-c61f8aa9-8f89-4b84-aad4-ec6cdc9d890d.png)
![image](https://user-images.githubusercontent.com/24869170/185582410-3f9e7a7c-71a2-47c3-8f8f-b29a538e61c9.png)
![image](https://user-images.githubusercontent.com/24869170/185582509-20e749f7-20fb-4a57-9f85-6f72f4405e9a.png)

**Comment by ntatfff** [comment]
Verified PASS on aura.network
![image](https://user-images.githubusercontent.com/24869170/185587729-dbc941a4-5ca1-467f-b9c6-cfa4c8f55d63.png)
![image](https://user-images.githubusercontent.com/24869170/185587818-cdc7491c-c26c-4ff7-bed6-d62a706db422.png)
![image](https://user-images.githubusercontent.com/24869170/185587965-cbdac795-c482-4817-8e04-79b750afde03.png)
![image](https://user-images.githubusercontent.com/24869170/185588112-f650d43c-29c9-4a73-8802-8c063004a49e.png)
