### ISSUE TITLE
Add new member for Our team

### ISSUE THREAD

**Issue by NgocAnh7278** [aura-nw/landing-page#291]
- [ ] Add information of Tuan Bass
Linkedin: https://www.linkedin.com/in/tuanba1/
Twitter: https://twitter.com/tuanbat

- [ ] Add twitter information of Thu Tran
Twitter: https://twitter.com/Thu_AuraNetwork

Link figma: https://www.figma.com/file/u9FVvZYiA6pTpoZYqmHpf1/%5BAura%5D-Landingpage?node-id=11602%3A8878

**Comment by NgocAnh7278** [comment]
> * [ ]  Add information of Tuan Bass
>   Linkedin: https://www.linkedin.com/in/tuanba1/
>   Twitter: https://twitter.com/tuanbat
> * [ ]  Add twitter information of Thu Tran
>   Twitter: https://twitter.com/Thu_AuraNetwork
> 
> Link figma: https://www.figma.com/file/u9FVvZYiA6pTpoZYqmHpf1/%5BAura%5D-Landingpage?node-id=11602%3A8878

**Comment by ntatfff** [comment]
Verified PASS on dev (06/09/2022)
![image](https://user-images.githubusercontent.com/24869170/188559858-c17b9aba-3807-4d98-8b20-568e2a95018b.png)
![image](https://user-images.githubusercontent.com/24869170/188559878-8cad9741-6db1-48eb-8b4b-0790ec76767e.png)

**Comment by ntatfff** [comment]
Verified PASS on aura.network
![image](https://user-images.githubusercontent.com/24869170/188572025-81e05338-37b5-49ec-9342-bb8cc0567bbd.png)
![image](https://user-images.githubusercontent.com/24869170/188572414-cc0984de-5bd2-43b4-ad03-2813fda94852.png)
