### ISSUE TITLE
Remove count down mainnet launch on landing page

### ISSUE THREAD

**Issue by NgocAnh7278** [aura-nw/landing-page#304]
![image](https://user-images.githubusercontent.com/40628286/191401062-cdfc9d88-d865-428e-9bb5-f946afef2139.png)

- [x] Remove count down mainnet launch
- [x] Update Thu Tran's image
Link figma: https://www.figma.com/file/u9FVvZYiA6pTpoZYqmHpf1/%5BAura%5D-Landingpage?node-id=11602%3A8878
Link image: https://drive.google.com/file/d/1ZpkqO-6eodqJ6Ospwn6aRJGks6picvgG/view

**Comment by Dpthao245** [comment]
PASS in Aura.network 21/09/2022
![DCCEC5B9-D35D-4690-91B8-BF4D016E0EA7](https://user-images.githubusercontent.com/72438169/191477648-8eda5568-7821-4352-a82b-860e4519eb74.jpg)


Desktop
![image](https://user-images.githubusercontent.com/72438169/191475990-ce16b7bf-a8ad-46e9-982e-7a7dc0997d84.png)
![image](https://user-images.githubusercontent.com/72438169/191476053-4b19bb71-eac2-4029-9b44-7aa2c8b9abfb.png)

Mobile
![23A3E81E-968C-403B-A52C-921A2A7AB139](https://user-images.githubusercontent.com/72438169/191477635-100e621b-a737-4a92-b952-244aec342b74.jpg)
