### ISSUE TITLE
[AuraNews] New Homepage

### ISSUE THREAD

**Issue by NgocAnh7278** [aura-nw/landing-page#64]
Link des: https://www.figma.com/file/u9FVvZYiA6pTpoZYqmHpf1/AuraNetwork---Landingpage?node-id=334%3A469

- [x] Header
- [x] Banner
- [x] List categories
- [x] Search news
- [x] List posts
- [x] Footer
- [x] Post details

**Comment by letrieuthien** [comment]
### Q&A:

1. Về hệ thống:

-  Hệ thống quản lý member login trong phạm vi trang news thôi đúng không?
- Chức năng comment sẽ ẩn đi nếu không login ?
- cần mô tả chức năng của icon BookMark trên mỗi thẻ bài viết
- form gửi email sau khi thực hiện xong việc send request thì có xử lý gì không? (thông báo hiện như thế nào?)
- Link Home trên header sẽ redirect về trang landing page?

2. Về giao diện:

- Màn hình đăng nhập của member ?
- Sau khi đăng nhập thì nút login trên header thay đổi như thế nào?
- chưa rõ khu vực icon này có mục đích gì, nếu là show số lượng thì con số như thế nào?
![image](https://user-images.githubusercontent.com/40551377/159855406-4ad30211-a5b0-4804-8d91-1ea222aada0c.png)

- ở màn hình nhỏ thì khu vực category tab này sẽ bị co lại, có thể đụng với ô search, hướng giải quyết như thế nào ?
![image](https://user-images.githubusercontent.com/40551377/159855657-93e8a0ff-1984-4569-b1ec-c7ff2822a099.png)

- Nút like ở các item comment có tác dụng gì nếu ko show ra được số lượng like?
![image](https://user-images.githubusercontent.com/40551377/159855879-e8f5ec30-a594-461c-b0de-d167c152ed13.png)

**Comment by Hanhi180300** [comment]
> Màn hình đăng nhập của member ?

-> Em chưa có thông tin về trang này ạ.
> chưa rõ khu vực icon này có mục đích gì, nếu là show số lượng thì con số như thế nào? (admin có quyền edit con số lại như 1 số liệu ảo ko?)

-> Dạ em cần biết mọi người có cần show số lượng hay không, tạm thời em để hide số lượng đi do hôm qua em Chi có request ẩn đi ạ.
> ở màn hình nhỏ thì khu vực category tab này sẽ bị co lại, có thể đụng với ô search, hướng giải quyết như thế nào ? (trường hợp nhiều category item quá thì sao?)

-> Chỗ này em sẽ thêm icon [->] khi có nhiều category, em sẽ update lại UI phần này ạ.
> Nút like ở các item comment có tác dụng gì nếu ko show ra được số lượng like? (nếu click vào để like thì nút này thay đổi như thế nào?)

-> Khi click like thì icon trái tim sẽ được filled ạ, em sẽ update thêm icon chỗ này.

**Comment by chiawesome** [comment]
> ### Q&A:
> 1. Về hệ thống:
> **News sẽ chuyển thành Aura Network Insights**
> * Hệ thống quản lý member login trong phạm vi trang news thôi đúng không?
> * Chức năng comment sẽ ẩn đi nếu không login ?
>   _Nếu ko login -> Click icon comment, hiển thị popup Login_
-> Tạm thời mình sẽ không để login account, bỏ hết các tim, comment và save (bookmark)
> * cần mô tả chức năng của icon BookMark trên mỗi thẻ bài viết
-> bỏ icon bookmark
> * form gửi email sau khi thực hiện xong việc send request thì có xử lý gì không? (thông báo hiện như thế nào?)
-> thông báo sẽ hiện "thank you for signing up", em sẽ request UI design 1 screen về phần này ạ
> * Link Home trên header sẽ redirect về trang landing page?
-> home sẽ nhảy về Aura Network Insights ạ 
> 2. Về giao diện:
> 
> * Màn hình đăng nhập của member ?
-> Bỏ không đăng nhập nữa ạ
> * Sau khi đăng nhập thì nút login trên header thay đổi như thế nào?
-> Bỏ không đăng nhập nữa ạ
> * chưa rõ khu vực icon này có mục đích gì, nếu là show số lượng thì con số như thế nào? (admin có quyền edit con số lại như 1 số liệu ảo ko?)
>   ![image](https://user-images.githubusercontent.com/40551377/159855406-4ad30211-a5b0-4804-8d91-1ea222aada0c.png)
-> Bỏ icon chỗ này 
> * ở màn hình nhỏ thì khu vực category tab này sẽ bị co lại, có thể đụng với ô search, hướng giải quyết như thế nào ? (trường hợp nhiều category item quá thì sao?)
>   ![image](https://user-images.githubusercontent.com/40551377/159855657-93e8a0ff-1984-4569-b1ec-c7ff2822a099.png)
-> UI bên chị Nhi đã có hướng giải quyết
> * Nút like ở các item comment có tác dụng gì nếu ko show ra được số lượng like? (nếu click vào để like thì nút này thay đổi như thế nào?)
>   ![image](https://user-images.githubusercontent.com/40551377/159855879-e8f5ec30-a594-461c-b0de-d167c152ed13.png)
> Bỏ icon chỗ này

**Comment by letrieuthien** [comment]
Q&A:
 --- News detail ----

- Số liệu Followers ở đây được lấy như thế nào? 
![image](https://user-images.githubusercontent.com/40551377/160064849-b9280f14-c484-46e0-95fd-5056a167f55a.png)
- cần làm rõ dãy link follow us on này
![image](https://user-images.githubusercontent.com/40551377/160065138-1758f633-1b15-4d22-9224-803f62bc3251.png)
 link này sẽ cấu hình chung với dãy link tại header/footer, hay là mỗi bài sẽ có 1 khu vực cho tác giả đưa link vào

**Comment by letrieuthien** [comment]
Help wanted
------------ Nhờ design hỗ trợ

1. Nhờ design group hình ngôi sao này vào background giúp dev (trang home của news)

![image](https://user-images.githubusercontent.com/40551377/160066998-335237f6-53ec-4688-ad7d-131582ed6663.png)

2. Nhờ design ẩn khu vực này do hiện tại không sử dụng nữa (trang news detail)
![image](https://user-images.githubusercontent.com/40551377/160067136-1f754727-defc-4501-8b3a-1c8083ecaf85.png)

**Comment by chiawesome** [comment]
> Q&A: --- News detail ----

> * Số liệu Followers ở đây được lấy như thế nào?
>   ![image](https://user-images.githubusercontent.com/40551377/160064849-b9280f14-c484-46e0-95fd-5056a167f55a.png)

-> mình bỏ cái đấy đi anh nhé, và để user name căn giữa đối xứng với avatar

> * cần làm rõ dãy link follow us on này
>   ![image](https://user-images.githubusercontent.com/40551377/160065138-1758f633-1b15-4d22-9224-803f62bc3251.png)
>   link này sẽ cấu hình chung với dãy link tại header/footer, hay là mỗi bài sẽ có 1 khu vực cho tác giả đưa link vào

-> nút này sẽ nhảy về các trang social chính của Aura ạ, giống header/footer ạ

> ---- Search page ----- *request: cần giao diện trang tìm kiếm nhé! (dạng danh sách kết quả và khi ko có kết quả)
> 
> * Đối với wordpress thì khi tìm kiếm , hệ thống sẽ lấy hết tất cả trang lẫn bài viết xuất ra dạng danh sách nếu có từ khóa cần tìm bên trong, dev cần xác nhận phạm vi tìm kiếm:
> 
> * tìm duy nhất tại news ?
> * tìm tất cả, hay tại các trang được yêu cầu (các trang đang trong quá trình lên kế hoạch sẽ đc cập nhật thêm)

-> cái này thì hiện mình sẽ chỉ hiển thị các kết quả bài tại trang insights ạ

**Comment by NgocAnh7278** [comment]
28/03/2022: Ngoc Anh BA updates:

- [ ] Cập nhật logo và tên website
![image](https://user-images.githubusercontent.com/40628286/160345807-8dd665bc-8dc1-41df-92e5-1bf5e987da88.png)

- [ ] Cập nhật đường link trang web
![image](https://user-images.githubusercontent.com/40628286/160345962-546b85cd-ddc3-486e-89c1-ccee541d5196.png)

- [ ] Header: hide labs và Guide, đổi logo Aura.network -> Aura.insights
![image](https://user-images.githubusercontent.com/40628286/160346502-263f31b7-6060-49e7-b9d2-dd1d307b8161.png)

- [ ] Chủ đề: hide Careers, NFT 101, Safe
![image](https://user-images.githubusercontent.com/40628286/160346704-f31cd048-31c8-4741-92d9-b9ac22afdacf.png)

- [ ] Bài viết: xóa bớt bài, chỉ để lại 2 bài có thumbnail: Ecomobi thumbnail và GBV thumbnail
Link thumbnail: https://drive.google.com/drive/folders/1ud3H-IAyZsVEcue-6myhKMTMxtHof3jK

- [ ] Chi tiết bài viết
- Sửa News -> Insights
![image](https://user-images.githubusercontent.com/40628286/160347189-7e87a7d5-5ee1-4a40-bd47-025a80f70313.png)
- Đổi font chữ cho Share post và related posts: giống font của header (Redig)
![image](https://user-images.githubusercontent.com/40628286/160348045-78e16a35-1131-407c-8574-d09c51b49bcd.png)
- Thêm icon của các loại social: telegram, twitter, facebook, pinterest, linkedin, tumblr
![image](https://user-images.githubusercontent.com/40628286/160349314-23e0c92f-f3bd-49a9-899d-a13a74bccdd9.png)

- [ ] Footer
- Hide labs và Guide
![image](https://user-images.githubusercontent.com/40628286/160349540-19179f76-6bd4-4fa3-99eb-56ea8a46f845.png)
- Cập nhật mô tả bên dưới "Never miss an opportunity!"
![image](https://user-images.githubusercontent.com/40628286/160349761-c9ea1469-8804-46df-9f3a-4de2858e52f2.png)
_Update_:
Sign up now for exclusive events, feature releases, announcements, plus few surprises!

**Comment by NgocAnh7278** [comment]
29/03/2022: Ngoc Anh BA updates:
Designer đã cập nhật một số thay đổi trên trang thiết kế
https://www.figma.com/file/u9FVvZYiA6pTpoZYqmHpf1/AuraNetwork---Landingpage?node-id=1946%3A9953

- [ ] Bổ sung category bên dưới title bài viết ở trang Home page trên Mobile
![image](https://user-images.githubusercontent.com/40628286/160587957-c82497cd-6cea-4264-bf80-a0114771e79e.png)

- [ ] Chuyển button Tìm kiếm lên header trang web: 
![image](https://user-images.githubusercontent.com/40628286/160588812-c21cccdb-3b55-4449-b73c-12f56c3c2ca4.png)
![image](https://user-images.githubusercontent.com/40628286/160588944-44280313-a61e-4337-a2b4-356baca57936.png)
- Trên desktop: 
B1: Click textbox Tìm kiếm -> show popup hiển thị Trending search và History search
B2: Nhập từ khóa cần tìm kiếm/ chọn 1 keywork trên popup 
B3: Hiển thị kết quả tìm kiếm
Nếu kết quả = 0 -> thông báo Không tìm thấy kết quả tìm kiếm.....
Nếu kết quả > 0 -> hiển thị tất cả các bài post 
- Trên mobile
B1: Click button icon Tìm kiếm -> show popup để nhập từ khóa và hiển thị Trending search và History search
B2: Nhập từ khóa cần tìm kiếm/ chọn 1 keywork trên popup 
B3: Hiển thị kết quả tìm kiếm
Nếu kết quả = 0 -> thông báo Không tìm thấy kết quả tìm kiếm.....
Nếu kết quả > 0 -> hiển thị tất cả các bài post

**Comment by NgocAnh7278** [comment]
31/03/2022: NgocAnh BA updates:

- [ ] Cập nhật banner trang Insights
https://www.figma.com/file/u9FVvZYiA6pTpoZYqmHpf1/AuraNetwork---Landingpage?node-id=2149%3A6562

**Comment by NgocAnh7278** [comment]
01/04/2022: Ngoc Anh BA updates:

- [ ] Cập nhật đoạn mô tả anh Giang Tran
![image](https://user-images.githubusercontent.com/40628286/161183835-1911ca5b-197a-46b5-a6f4-f4d05c8296a5.png)
_Update_:
As a Forbes Technology Council member, Giang has deep expertise in Cloud and Blockchain. He is the ex-founder of akaChain and has guided many successful start-ups. Giang drives Aura's strategy adoption and equitable growth.

- [ ] Footer: Bỏ địa chỉ Headquarter:
![image](https://user-images.githubusercontent.com/40628286/161183947-5842a963-6104-4f53-a0cd-349ba3499036.png)

**Comment by NgocAnh7278** [comment]
06/04/2022: Ngoc Anh BA updates:

- [ ] Cập nhật banner insights
Link des: https://www.figma.com/file/u9FVvZYiA6pTpoZYqmHpf1/AuraNetwork---Landingpage?node-id=3284%3A8560

**Comment by NgocAnh7278** [comment]
07/04/2022: Ngoc Anh BA updates:

- [ ] Tìm kiếm:

- Flow tìm kiếm: https://drive.google.com/file/d/1KhDj6xBLjqcXMuKy8-E438R9vsSGLQ4k/view
- Link des: https://www.figma.com/file/u9FVvZYiA6pTpoZYqmHpf1/AuraNetwork---Landingpage?node-id=1946%3A10106

- [ ] Bổ sung tags trong chi tiết bài viết:
- Khi đăng bài, marketing sẽ bổ sung các hashtag của bài viết
- Trên trang insights, các hashtag sẽ nằm ở cuối bài viết chi tiết.
Click 1 hashtag -> hiển thị DS các bài viết có chứa hashtag đó.
