### ISSUE TITLE
[LandingPage] Image is different color with theme on desktop

### ISSUE THREAD

**Issue by NgocAnh7278** [aura-nw/landing-page#81]
**Describe the bug**
Image spaceman near footer is different color with theme.
Image's color: black
Image's theme: gray

**To Reproduce**
1. Go to https://aura.network/ on mobile phone
2. Go to FAQs, below the image spaceman 

**Expected behavior**
Theme and image of spaceman are the same color

**Screenshots**
![image](https://user-images.githubusercontent.com/40628286/159897828-865b5039-59a0-4d93-99c6-8a8b6cf1a839.png)
![image](https://user-images.githubusercontent.com/40628286/159897873-efcdb727-3857-4dc1-b6eb-fded73a41d3d.png)

**Desktop** (please complete the following information):
Browser: chrome

**Comment by hangpham23** [comment]
![7](https://user-images.githubusercontent.com/102220123/160108507-e087b64e-5334-4b36-898e-50d63472efc0.jpg)
<img width="1009" alt="Screen Shot 2022-03-25 at 17 55 08" src="https://user-images.githubusercontent.com/102220123/160108575-9d3a55f8-0f40-434b-88b2-5b2e8b995153.png">
verified!
